;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;                                                                            ;
;                                   timer.inc                                ;
;                          Timing Routines Include File                      ;
;                                                                            ;
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

; This file contains the definitions for the timing functions defined in
; timer.asm.
;
; Revision History:
;     9/30/13  Glen George      initial revision
;     4/30/18  Glen George      updated comments




;delay timer constants
.EQU	TIMER_CNT = 5			;number of delay timers
